export const CREATE_AUCTION = "CREATE_AUCTION";
export const LOAD_AUCTIONS_SUCCESS = "LOAD_AUCTIONS_SUCCESS";
export const UPDATE_AUCTION_SUCCESS = "UPDATE_AUCTION_SUCCESS";
export const CREATE_AUCTION_SUCCESS = "CREATE_AUCTION_SUCCESS";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
