export const CREATE_AUCTION = "CREATE_AUCTION";
export const LOAD_AUCTIONS_SUCCESS = "LOAD_AUCTIONS_SUCCESS";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS";
