const auctions = [
  {
    id: 1,
    title: "Securing React Apps with Auth0",
    description: "react-auth0-authentication-security",
    startPrice: 0,
    currentBid: 0,
    endsAt: 0,
    deliveryType: "",
    tags: [],
    user: 1,
    category: 5,
  },
  {
    id: 2,
    title: "React: The Big Picture",
    description: "react-big-picture",
    startPrice: 0,
    currentBid: 0,
    endsAt: 0,
    deliveryType: "",
    tags: [],
    user: 1,
    category: 10,
  },
  {
    id: 3,
    title: "Creating Reusable React Components",
    description: "react-creating-reusable-components",
    startPrice: 0,
    currentBid: 0,
    endsAt: 0,
    deliveryType: "",
    tags: [],
    user: 1,
    category: 1,
  },
  {
    id: 4,
    title: "Building a JavaScript Development Environment",
    description: "javascript-development-environment",
    startPrice: 0,
    currentBid: 0,
    endsAt: 0,
    deliveryType: "",
    tags: [],
    user: 1,
    category: 2,
  },
  {
    id: 5,
    title: "Building Applications with React and Redux",
    description: "react-redux-react-router-es6",
    startPrice: 0,
    currentBid: 0,
    endsAt: 0,
    deliveryType: "",
    tags: [],
    user: 1,
    category: 1,
  },
  {
    id: 6,
    title: "Building Applications in React and Flux",
    description: "react-flux-building-applications",
    startPrice: 0,
    currentBid: 0,
    endsAt: 0,
    deliveryType: "",
    tags: [],
    user: 1,
    category: 7,
  },
  {
    id: 7,
    title: "Clean Code: Writing Code for Humans",
    description: "writing-clean-code-humans",
    startPrice: 0,
    currentBid: 0,
    endsAt: 0,
    deliveryType: "",
    tags: [],
    user: 1,
    category: 6,
  },
  {
    id: 8,
    title: "Architecting Applications for the Real World",
    description: "architecting-applications-dotnet",
    startPrice: 0,
    currentBid: 0,
    endsAt: 0,
    deliveryType: "",
    tags: [],
    user: 1,
    category: 6,
  },
  {
    id: 9,
    title: "Becoming an Outlier: Reprogramming the Developer Mind",
    description: "career-reboot-for-developer-mind",
    startPrice: 0,
    currentBid: 0,
    endsAt: 0,
    deliveryType: "",
    tags: [],
    user: 1,
    category: 4,
  },
  {
    id: 10,
    title: "Web Component Fundamentals",
    description: "web-components-shadow-dom",
    startPrice: 0,
    currentBid: 0,
    endsAt: 0,
    deliveryType: "",
    tags: [],
    user: 1,
    category: 8,
  },
];

const users = [
  { id: 1, name: "Cory House" },
  { id: 2, name: "Scott Allen" },
  { id: 3, name: "Dan Wahlin" },
];

const categories = [
  { id: 1, name: "Clothes" },
  { id: 2, name: "Furniture" },
  { id: 3, name: "Baby stuff" },
  { id: 4, name: "Hobbies" },
  { id: 5, name: "Electronics" },
  { id: 6, name: "PC & Games" },
  { id: 7, name: "Accessories" },
  { id: 8, name: "Vehicles" },
  { id: 9, name: "Appliances" },
  { id: 10, name: "Misc" },
];

const newAuction = {
  id: null,
  title: "",
  startPrice: 0,
  currentBid: 0,
  endsAt: 0,
  deliveryType: "",
  tags: [],
  user: null,
  category: null,
};

// Using CommonJS style export so we can consume via Node (without using Babel-node)
module.exports = {
  newAuction,
  auctions,
  users,
  categories,
};
